version: "3.4"

services:

  nginx:
    build: ./docker/nginx
    image: districts-nginx
    depends_on:
      - php-fpm
    ports:
      - "${HTTP_PORT-8080}:80"

  assets-nginx:
    build: ./docker/assets-nginx
    image: districts-assets-nginx
    ports:
      - "${ASSETS_HTTP_PORT-8180}:80"
    volumes:
      - ./public/assets:/var/www/html

  php-fpm:
    build: ./docker/php-fpm
    image: districts-php
    depends_on:
      - sql
      - assets-nginx
    environment:
      DB_URL: mysql://dev_user:dev_password@sql/dev_db
      ASSETS_URL: "http://127.0.0.1:${ASSETS_HTTP_PORT-8180}"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000"
      XDEBUG_MODE: debug
    volumes:
      - .:/var/www/html
    extra_hosts:
      host.docker.internal: host-gateway

  php-tools:
    profiles:
      - dev-task # not really a service, don't start by default
    build: ./docker/php-tools
    image: districts-php-tools
    volumes:
      - .:/app

  sql:
    image: mariadb:10.5
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_password
    volumes:
      - mariadb-dev-sql-data:/var/lib/mysql

volumes:
  mariadb-dev-sql-data:
    name: districts-mariadb-dev-sql-data
