name: tests

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build containers
      run: docker compose build
    - name: Install dependencies
      run: docker compose run -T --rm php-fpm composer install
    - name: Test
      run: docker compose run -T --rm php-fpm composer test-cover-ci
